### ISSUE TITLE
No module named 'roslaunch'

### ISSUE THREAD

**Issue by omar-mostafa81** [DDTRobot/diablo_ros2#8]
I have two ros versions on my VM, ros-noetic for ROS1 and ros-foxy for ROS2. I have sourced the diablo_ws for ros-foxy and colcon to build the package, but when I try to launch any of the launch files in the simulation package, I receive the following error:

Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=InvalidLaunchFileError('py')>
Traceback (most recent call last):
  File "/home/omar/.local/lib/python3.8/site-packages/xacro/__init__.py", line 185, in eval_extension
    from roslaunch import substitution_args
ModuleNotFoundError: No module named 'roslaunch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 53, in get_launch_description_from_any_launch_file
    return loader(launch_file_path)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_file_utilities.py", line 68, in get_launch_description_from_python_launch_file
    return getattr(launch_file_module, 'generate_launch_description')()
  File "/home/omar/diablo_ws/install/diablo_simulation/share/diablo_simulation/launch/ctrl.launch.py", line 15, in generate_launch_description
    robot_description_config = xacro.process_file(xacro_file)
  File "/home/omar/.local/lib/python3.8/site-packages/xacro/__init__.py", line 1020, in process_file
    process_doc(doc, **kwargs)
  File "/home/omar/.local/lib/python3.8/site-packages/xacro/__init__.py", line 967, in process_doc
    eval_all(doc.documentElement, macros, symbols)
  File "/home/omar/.local/lib/python3.8/site-packages/xacro/__init__.py", line 839, in eval_all
    process_include(node, macros, symbols, eval_all)
  File "/home/omar/.local/lib/python3.8/site-packages/xacro/__init__.py", line 420, in process_include
    for filename in get_include_files(filename_spec, symbols):
  File "/home/omar/.local/lib/python3.8/site-packages/xacro/__init__.py", line 371, in get_include_files
    filename_spec = abs_filename_spec(eval_text(filename_spec, symbols))
  File "/home/omar/.local/lib/python3.8/site-packages/xacro/__init__.py", line 628, in eval_text
    results.append(handle_extension(lex.next()[1][2:-1]))
  File "/home/omar/.local/lib/python3.8/site-packages/xacro/__init__.py", line 618, in handle_extension
    return eval_extension("$(%s)" % eval_text(s, symbols))
  File "/home/omar/.local/lib/python3.8/site-packages/xacro/__init__.py", line 189, in eval_extension
    raise XacroException("substitution args not supported: ", exc=e)
xacro.XacroException: substitution args not supported:  No module named 'roslaunch'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/include_launch_description.py", line 130, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_source.py", line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_description_source.py", line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 56, in get_launch_description_from_any_launch_file
    raise InvalidLaunchFileError(extension, likely_errors=exceptions)
launch.invalid_launch_file_error.InvalidLaunchFileError: Caught exception when trying to load file of format [py]: substitution args not supported:  No module named 'roslaunch'

I have deleted the ros-noetic version permanently guessing the issue is related to it, but the same error occurs. I hope anyone can help with that.

**Comment by sun-rabbit** [comment]
ros2

**Comment by sun-rabbit** [comment]
ros2 launch

**Comment by Dantemiwa** [comment]
This issued is solved and closed.
